# compose.yaml
# version: 24.10.31
#
# Usage
#
# Example in Bash
#
#   # Configuration for APM
#   export RIVERBED_APM_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   export RIVERBED_APM_CUSTOMER_ID="12341234-12341234-13241234"
#
#   # Optional configuration for UJI
#   export ALLUVIO_UJI_TAG="<script id=ALLUVIO-Aternity-UJI src=http:\/\/my-UJI-tag-prefix-flyfast\.btttag\.com\/btt\.js><\/script>"
#
#   # Start containers
#   docker compose up
#
# Example in PowerShell
#
#   # Configuration for APM
#   $env:RIVERBED_APM_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   $env:RIVERBED_APM_CUSTOMER_ID="12341234-12341234-13241234"
#
#   # Optional configuration for UJI
#   $env:ALLUVIO_UJI_TAG="<script id=ALLUVIO-Aternity-UJI src=http:\/\/my-UJI-tag-prefix-flyfast\.btttag\.com\/btt\.js><\/script>"
#
#   # Start containers
#   docker compose up

services:

  apm-collector:
    image: registry.hub.docker.com/aternity/apm-collector:latest
    container_name: apm-collector
    environment:
      SERVER_URL: "wss://${RIVERBED_APM_SERVER_HOST}/?RPM_AGENT_CUSTOMER_ID=${RIVERBED_APM_CUSTOMER_ID}"
    ports:
      # Uncomment the telemetry protocol used by the application

      # OpenTelemetry, https://opentelemetry.io
      # - "4317:4317/tcp"   # OpenTelemetry OTLP over gRPC
      # - "4318:4318/tcp"     # OpenTelemetry OTLP JSON/Protobuf over HTTP
      - "55681:55681/tcp" # OpenTelemetry OTLP JSON/Protobuf over HTTP
      
      # Jaeger, https://www.jaegertracing.io
      # - "14268:14268/tcp" # Jaeger Thrift Binary over HTTP
      # - "6831:6831/udp"   # Jaeger Thrift Compact
      # - "6832:6832/udp"   # Jaeger Thrift Binary
      
      # Zipkin, https://zipkin.io
      # - "9411:9411/tcp"   # Zipkin v2 json/protobuf and v1 json/thrift
      # - "5775:5775/udp"   # Jaeger's Thrift support for Zipkin v1

  flyfast-flightsearch:
    build: ./FlyFast-FlightSearch
    depends_on:
      - apm-collector
    container_name: flyfast-flightsearch
    environment:
      COLLECTOR_URL: http://apm-collector:55681/v1/traces
    ports:
      - "8080:8080"

  flyfast-webui:
    build: ./FlyFast-WebUI
    depends_on:
      - flyfast-flightsearch
      - apm-collector
    container_name: flyfast-webui
    environment:
      REACT_APP_FLIGHT_SEARCH: http://flyfast-flightsearch:8080
      REACT_APP_OPENTELEMETRY_ENDPOINT: http://apm-collector:55681
      ALLUVIO_UJI_TAG: ${ALLUVIO_UJI_TAG}
    ports:
      - "80:80"
